### ISSUE TITLE
Usage guide

### ISSUE THREAD

**Issue by MrOutis** [chuycepeda/mboilerplate#1]
- [ ] Installation process
  + [ ] What dependencies to install
  + [ ] Setup Google App Engine
- [ ] Where do I put my code
  + [ ] File structure
- [ ] How to run the whole thing
- [ ] How to toggle integrations (CartoDB, Slack, etc.)

**Comment by chuycepeda** [comment]
Hello MrOutis !

Definitely I should build this, I have some video tutorials pending to share through the live website. If you want to get it up an running just follow the "Get Started" at https://github.com/coto/gae-boilerplate

This boilerplate is essentially the same, just fancier and with a bit more integrations. You'll see config.py files doing the magic, there's still a lot work to do but it gets you reeeally fast on track instead of starting from scratch.

Wanna help ?

**Comment by MrOutis** [comment]
Awesome, I'll check it out. In a week or two you'll have some wild pull requests :beers:.
Please, keep me updated with the videos!

**Comment by chuycepeda** [comment]
Hello MrOutis !

Had the time to update some stuff, installation process brought to readme.md from the original coto's repo, which is practically same process with just updated links.

File structure is also described in a very simple approach, bp_admin stands for /admin/ route, bp_contents for your main app, and bp_includes for the current implementation as is.

About toggling integrations, you'll see at bp_includes config.py file your variables, most of them operate either at base layouts or specific html files for demoing purposes. You can do a search for 'slack' or 'cartodb' and easily get what I've done to demo.

Hope this gets better for using it.

PS.- 
Video 1 for instance creation (7min): https://www.youtube.com/watch?v=l7fc8rLUOjM
Video 2 for folder structure (3min): https://www.youtube.com/watch?v=k6KdmDc9tGs

**Comment by MrOutis** [comment]
This is amazing, dude, thank you!
